### ISSUE TITLE
tun2socks udpgw doesn't work with linux 3.19

### ISSUE THREAD

**Issue by felixonmars** [ambrop72/badvpn#7] opened 2015-02-18 14:57 UTC
I am getting a problem when running tun2socks with linux 3.19. badvpn-tun2socks process takes 100% CPU, and there are no udpgw messages in stdout. TCP tunneling seems to work well, but UDP doesn't. A Ctrl-C or SIGTERM could not terminate the program either, only SIGKILL would do. Downgrading linux kernel to 3.18.x fixes all this.

**Comment by LazyZhu** [comment] 2015-02-25 08:55
You can try this `udprelay` version: https://github.com/LazyZhu/badvpn/tree/udprelay
I merged @linusyang's https://github.com/linusyang/badvpn/commit/c7692ff37bddec3b0274692478874eba29c93eef to the master.

**Comment by ladf** [comment] 2015-04-08 14:45
Hi, 
This bug is a big problem, running Arch Linux. 
We've tried the suggested udprelay version but it does not help.

**Comment by ambrop72** [comment] 2015-04-09 10:40
Workaround implemented in 92a2fc831bc5d1293c0d07c4afae055470ebc7a2, and included in new release 1.999.130.
The cause is a breaking change of behavior of the TUN/TAP device in kernel 3.19: https://bugzilla.kernel.org/show_bug.cgi?id=96381

**Closed by ambrop72** 2015-04-09 10:40 UTC

**Comment by felixonmars** [comment] 2015-04-09 10:50
Thanks! The new version works fine for me.

**Comment by ladf** [comment] 2015-04-09 11:21
Excellent, thanks!
