### ISSUE TITLE
INFO(SocksUdpGwClient): SOCKS up     INFO(SocksUdpGwClient): SOCKS error

### ISSUE THREAD

**Issue by TongxiJi** [ambrop72/badvpn#27] opened 2016-09-01 14:35 UTC
This is appeared from tun2socks.exe with "--udpgw-remote-server-addr 127.0.0.1:7300" and the version is 1.999.128.
The remote server is ubuntu 14.04 and set up udpgw(v1.999.129) on it.
What happened,or something i can do to solve it.

> INFO(tun2socks): UDP: from device 42 bytes
> INFO(tun2socks): UDP: from device 33 bytes
**> INFO(SocksUdpGwClient): SOCKS up**
> INFO(tun2socks): UDP: from device 33 bytes
> INFO(tun2socks): UDP: from device 34 bytes
> INFO(tun2socks): UDP: from device 42 bytes
> INFO(tun2socks): UDP: from device 33 bytes
> INFO(tun2socks): UDP: from device 33 bytes
> INFO(tun2socks): UDP: from device 33 bytes
> INFO(tun2socks): UDP: from device 33 bytes
> INFO(tun2socks): UDP: from device 34 bytes
> INFO(tun2socks): UDP: from device 34 bytes
> INFO(tun2socks): UDP: from device 33 bytes
> INFO(tun2socks): UDP: from device 34 bytes
**> INFO(SocksUdpGwClient): SOCKS error**
> INFO(tun2socks): UDP: from device 34 bytes

**Comment by ambrop72** [comment] 2016-09-01 16:20
Hey,
I doubt this is an issue in tun2socks. From the log file all that is known is that the connection between tun2socks and udpgw (which is a TCP connection through the SOCKS proxy) had been broken. You should investigate this more deeply, I can't say much from just this log.

**Comment by TongxiJi** [comment] 2016-09-02 01:43
Thanks for the reply.
And i forgot to say that  i use tun2socks.exe to work with shadowsocks(https://github.com/shadowsocks/shadowsocks-windows/tree/master).
Maybe shadowsocks-windows client just works well with standard socks5.Anyway i'm not sure and i will hava a test.

**Comment by TongxiJi** [comment] 2016-09-02 05:21
I've tested .
The result is  that tun2socks.exe works well with a standard socks5 server.

**Comment by hillz1** [comment] 2016-09-03 07:06
I'm facing the same issue, a few days ago everything worked well, I didn't change any of my configuration but somehow that error popped up. I have no idea what went wrong, anyone who have solved this issue please let me know, in the mean time this is my tun2socks command that used to work:

`badvpn-tun2socks --tundev tun1 --netif-ipaddr 10.0.0.2 --netif-netmask 255.255.255.0 --socks-server-addr 192.168.1.1:1080 --udpgw-remote-server-addr 192.168.1.1:7300`

I'm running this on openwrt.

**Comment by ambrop72** [comment] 2016-09-03 07:53
Hey everyone,
I really cannot say anything here without more detailed information, like logs of udpgw, wireshark traces etc.

**Comment by hillz1** [comment] 2016-09-03 08:00
How do I log the udpgw ? Sorry, I'm just a new linux user.

**Comment by ambrop72** [comment] 2016-09-03 08:01
@hillz1 the original bug report is related to using udpgw for UDP forwarding. In that case you start udpgw with option --loglevel debug. If you're not using udpgw then still do the same for tun2socks.

**Comment by hillz1** [comment] 2016-09-03 08:06
Here's my wireshark log: https://ufile.io/99e05

**Comment by hillz1** [comment] 2016-09-03 08:10
Here's the debug log:

`NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
DEBUG(BReactor): Reactor initializing
DEBUG(BSignal): BSignal initializing
NOTICE(tun2socks): entering event loop
DEBUG(BReactor): Entering event loop
DEBUG(tun2socks): lwip init
DEBUG(tun2socks): netif func init
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait returned 1 file descriptors
DEBUG(BReactor): Dispatching file descriptor
DEBUG(BSocksClient): connected
DEBUG(BSocksClient): sent hello
DEBUG(BSocksClient): received hello
DEBUG(BSocksClient): no authentication
DEBUG(BSocksClient): sent request
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait returned 1 file descriptors
DEBUG(BReactor): Dispatching file descriptor
DEBUG(tun2socks): device: received packet
INFO(tun2socks): UDP: from device 48 bytes
DEBUG(tun2socks): device: received packet
INFO(tun2socks): UDP: from device 48 bytes
DEBUG(tun2socks): device: received packet
INFO(tun2socks): UDP: from device 48 bytes
DEBUG(tun2socks): device: received packet
INFO(tun2socks): UDP: from device 48 bytes
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait returned 1 file descriptors
DEBUG(BReactor): Dispatching file descriptor
DEBUG(tun2socks): device: received packet
INFO(tun2socks): UDP: from device 28 bytes
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait returned 1 file descriptors
DEBUG(BReactor): Dispatching file descriptor
DEBUG(tun2socks): device: received packet
INFO(tun2socks): UDP: from device 28 bytes
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait returned 1 file descriptors
DEBUG(BReactor): Dispatching file descriptor
DEBUG(BUnixSignal): dispatching signal 2
DEBUG(BSignal): Dispatching signal
NOTICE(tun2socks): termination requested
NOTICE(tun2socks): tearing down
DEBUG(BReactor): Exiting event loop, exit code 1
DEBUG(BReactor): Reactor freeing
NOTICE(tun2socks): exiting
`

**Comment by ambrop72** [comment] 2016-09-03 08:15
@hillz1 there is nothing really interesting in these logs, the later log seems to show a SOCKS connection successfully set up but nothing more, than receiving a few UDP packets (and they must be getting ignored since you don't have udpgw setup).

**Comment by hillz1** [comment] 2016-09-03 08:16
> (and they must be getting ignored since you don't have udpgw setup).

How do I set up udpgw ?

**Comment by ambrop72** [comment] 2016-09-03 08:20
@hillz1 I am not sure what you want to do in the first place and what the issue is. 
The old tun2socks guide that used to be on Google Code can still be found here: https://github.com/ambrop72/badvpn-googlecode-export/blob/wiki/tun2socks.md

**Comment by hillz1** [comment] 2016-09-03 08:34
The issue is that my internet isn't working like it used to be, is it possible that the error is caused by the server side that is not running `badvpn-udpgw --listen-addr 127.0.0.1:7300` ?

Here's the error on my browser looks like: https://s13.postimg.org/h1fox06pj/Screenshot_2016_09_03_15_32_25.png

**Comment by ambrop72** [comment] 2016-09-03 08:38
@hillz1 if you want to forward DNS through, then yes you should use udpgw setup as described.

**Comment by hillz1** [comment] 2016-09-03 08:42
I'm kinda sure it's the server side error, I must forward the DNS or if I don't my internet won't work.
@TongxiJi are you also using SSH accounts from fastssh.com ?

**Comment by TongxiJi** [comment] 2016-09-03 09:00
@hillz1 im using my shadowsocks server,and i have set up udpgw on my server

**Comment by hillz1** [comment] 2016-09-03 09:10
@ambrop72 after a while, I found out that badvpn-tun2socks always closes on its own:

`DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait timed out
DEBUG(BReactor): Dispatching timer
DEBUG(tun2socks): TCP timer
DEBUG(BReactor): Calling epoll_wait
DEBUG(BReactor): epoll_wait returned 1 file descriptors
DEBUG(BReactor): Dispatching file descriptor
DEBUG(BUnixSignal): dispatching signal 15
DEBUG(BSignal): Dispatching signal
NOTICE(tun2socks): termination requested
NOTICE(tun2socks): tearing down
DEBUG(BReactor): Exiting event loop, exit code 1
DEBUG(BReactor): Reactor freeing
NOTICE(tun2socks): exiting`

It always closes on its own even after I restart it many times. Do yo know why?

**Comment by ambrop72** [comment] 2016-09-03 09:13
@hillz1 the logs tell that something is sending SIGTERM (15) signal to tun2socks which exists in response.

**Comment by TongxiJi** [comment] 2016-09-03 10:19
@ambrop72    tun2socks.exe(1.999.128) + shadowsocks + udpgw(ubuntu,1.999.129,set up on the shadowsocks server)
Full repeat log can be seen from attach file.

C:\XXXX\badvpn-tun2socks.exe  --tundev tap0901:MoteorSpeeder:192.168.179.1:192.168.179.0:255.255.255.0 --netif-ipaddr 192.168.179.2 --netif-netmask 255.255.255.0 --socks-server-addr 127.0.0.1:1080 --udpgw-remote-server-addr 127.0.0.1:7300

badvpn-udpgw --listen-addr 127.0.0.1:7300

[Uploading tun2socks-windows.txt…]()

**Comment by hillz1** [comment] 2016-09-04 08:07
@ambrop72 this is my ssh log:

> debug1: Connection to port 1080 forwarding to socks port 0 requested.
> debug1: channel 1: new [dynamic-tcpip]
> channel 1: open failed: connect failed: 
> debug1: channel 1: free: direct-tcpip: listening port 1080 for 192.168.1.1 port 7300, connect from 192.168.1.1 port 44880 to 192.168.1.1 port 1080, nchannels 2
> debug1: Connection to port 1080 forwarding to socks port 0 requested.
> debug1: channel 1: new [dynamic-tcpip]
> channel 1: open failed: connect failed: 
> debug1: channel 1: free: direct-tcpip: listening port 1080 for 192.168.1.1 port 7300, connect from 192.168.1.1 port 44881 to 192.168.1.1 port 1080, nchannels 2
> debug1: Connection to port 1080 forwarding to socks port 0 requested.
> debug1: channel 1: new [dynamic-tcpip]

Do you see something wrong with that log ?

**Comment by ambrop72** [comment] 2016-09-04 08:18
@hillz1 the log says that connections from ssh to remote hosts are failing ("channel 1: open failed: connect failed"). Upon this ssh must be closing the associated SOCKS connections from tun2socks, hence you would see "SOCKS error" or "SOCKS closed" from tun2socks.

Since there is no indication for a bug in tun2socks, I am closing this. Sorry I am not a support channel for ssh/networking.

**Closed by ambrop72** 2016-09-04 08:18 UTC
